import { Container, Typography } from "@components/ui";
import Image from "next/image";

export const Features = () => {
  return (
    <section className="features" id="features">
      <div className="features__decor">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="1140"
          height="1124"
          viewBox="0 0 1140 1124"
          fill="none"
        >
          <path
            d="M1106.07 213.92L1094.41 207.114L1106.07 213.92ZM705.168 1118.71L717.877 1123.26L726.986 1097.85L714.277 1093.29L705.168 1118.71ZM5.17509 87.841C221.491 52.5272 535.94 19.5471 776.079 29.2037C896.645 34.052 996.264 49.6024 1055.56 79.5271C1085.05 94.41 1102.56 111.842 1109.26 131.342C1115.84 150.531 1113.08 175.123 1094.41 207.114L1117.73 220.727C1138.73 184.741 1144.82 151.782 1134.79 122.578C1124.88 93.6856 1100.34 71.8837 1067.72 55.423C1002.81 22.6605 898.019 7.08539 777.164 2.2255C534.458 -7.53427 218.005 25.7389 0.824905 61.1938L5.17509 87.841ZM1094.41 207.114C1045.38 291.104 975.443 381.115 902.755 471.325C830.342 561.196 755.113 651.354 696.675 734.589C638.58 817.332 595.129 895.821 588.825 962.431C585.615 996.343 591.964 1027.82 611.341 1054.95C630.567 1081.87 661.609 1103.1 705.168 1118.71L714.277 1093.29C673.994 1078.85 648.34 1060.29 633.313 1039.25C618.439 1018.43 612.979 993.776 615.705 964.975C621.271 906.16 660.662 832.869 718.772 750.103C776.538 667.827 850.876 578.745 923.78 488.266C996.41 398.126 1067.55 306.68 1117.73 220.727L1094.41 207.114Z"
            fill="#4f2d9f"
          />
        </svg>
      </div>
      <Container>
        <div className="features__wrapper stack column">
          <Typography className="h2" weight="500" tag="h2" center>
            Core Features
          </Typography>

          <ul className="features__list">
            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/search.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Google & Bing Compatible
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Whether you’re aiming for Google’s first page or boosting Bing
                rankings, Ghost Reach works seamlessly with both major search
                engines. It replicates user behavior on Google and Bing SERPs,
                expanding your reach on all fronts.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/human.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Fully Emulated Human Behavior
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Every click is generated by a headless browser that behaves like
                a real user – random mouse movements, realistic typing,
                scrolling, pausing, and varied browsing patterns are all in
                play. This human-like interaction ensures the clicks are
                indistinguishable from genuine visitors.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/location.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Geo-Targeting & Fingerprint Spoofing
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Ghost Reach lets you target specific countries, regions, or
                cities for your clicks. It rotates through a pool of diverse IPs
                and device fingerprints, so each session looks like it’s coming
                from a different real user in your chosen location. (IP
                geolocation, user-agent, screen resolution, OS, language – all
                randomized per campaign settings.)
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/language.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Multi-Language Support
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Optimize for any locale. Our system can perform searches on
                Google/Bing across different language settings, emulating local
                users in any language market you need. Great for international
                SEO campaigns that require native-language queries.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/browser.png"
                    width="40"
                    height="40"
                    alt="browser"
                    loading="lazy"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Aged Browser Profiles with Context
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Ghost Reach uses browser instances that have aged histories –
                bookmarks, cookies, logins, and past browsing data all related
                to your website and keyword, drastically enhancing results. To
                search engines, these look like long-term real users conducting
                their regular searches that happen to favor your site.
              </Typography>
            </li>
          </ul>
          <button className="features__button button">Start for Free</button>
        </div>
      </Container>
    </section>
  );
};
