import { Container, Typography } from "@components/ui";
import Image from "next/image";

export const Features = () => {
  return (
    <section className="features" id="features">
      <Container>
        <div className="features__wrapper stack column">
          <Typography className="h2" weight="500" tag="h2" center>
            Core Features
          </Typography>

          <ul className="features__list">
            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/search.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Google & Bing Compatible
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Whether you’re aiming for Google’s first page or boosting Bing
                rankings, Ghost Reach works seamlessly with both major search
                engines. It replicates user behavior on Google and Bing SERPs,
                expanding your reach on all fronts.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/human.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Fully Emulated Human Behavior
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Every click is generated by a headless browser that behaves like
                a real user – random mouse movements, realistic typing,
                scrolling, pausing, and varied browsing patterns are all in
                play. This human-like interaction ensures the clicks are
                indistinguishable from genuine visitors.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/location.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Geo-Targeting & Fingerprint Spoofing
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Ghost Reach lets you target specific countries, regions, or
                cities for your clicks. It rotates through a pool of diverse IPs
                and device fingerprints, so each session looks like it’s coming
                from a different real user in your chosen location. (IP
                geolocation, user-agent, screen resolution, OS, language – all
                randomized per campaign settings.)
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/language.png"
                    width="40"
                    height="40"
                    alt="browser"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Multi-Language Support
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Optimize for any locale. Our system can perform searches on
                Google/Bing across different language settings, emulating local
                users in any language market you need. Great for international
                SEO campaigns that require native-language queries.
              </Typography>
            </li>

            <li className="features__item stack column">
              <div className="features__item-top stack column">
                <div className="features__item-image">
                  <Image
                    src="/img/features/browser.png"
                    width="40"
                    height="40"
                    alt="browser"
                    loading="lazy"
                  />
                </div>
                <Typography
                  className="features__item-title"
                  weight="500"
                  tag="h3"
                >
                  Aged Browser Profiles with Context
                </Typography>
              </div>
              <Typography className="p" tag="p">
                Ghost Reach uses browser instances that have aged histories –
                bookmarks, cookies, logins, and past browsing data all related
                to your website and keyword, drastically enhancing results. To
                search engines, these look like long-term real users conducting
                their regular searches that happen to favor your site.
              </Typography>
            </li>
          </ul>
          <button className="features__button button">Start for Free</button>
        </div>
      </Container>
    </section>
  );
};
